### ISSUE TITLE
The superlatives, When support Mac OS 10.15?

### ISSUE THREAD

**Issue by AminHu** [AMD-OSX/AMD_Vanilla#44]
Mac 10.15 already released today.

**Comment by EfraimLA** [comment]
Yes, i'd tried with previous config but couldn't boot, really Clover will die? What should i do? Try OpenCore? 

I'm waiting for the new config patch, btw thanks a lot for the support

**Comment by SchmockLord** [comment]
10.15 Support has been added just 10min ago.

**Comment by EfraimLA** [comment]
thx <3

**Comment by vwxyzjn** [comment]
The guide here https://vanilla.amd-osx.com/ Still says it only supports 10.13 and 10.14 though...

**Comment by zalivar71** [comment]
Guys, I update my config of Clover in Ryzen, run update for MacOS 10.15
And stuck on update. It seems like update begin to install, because I can't to boot to System, only boot Installer of update via Clover
Stuck in console. GPU not started. After long time system automaticly reboot.

In begin of boot I see warning:
AMF: Only 160/256 slide values are usable
Valid slides 80-256


I try to add clear config for Clover - and got Kernel Panic

**Comment by zalivar71** [comment]
My problem was with AMD RX 580. I download fresh _WhateverGreen_ and _Lilu_. System was broken and I installed OS with installer and finished my update. Also I leave _NullCPUPowerManagement.kext_
Additionaly I install from Clover _CPUFriend.kext_ and _VirtualSMC.kext_ 
I'm not sure that I need all this kexts,  but have no time to test this moment

**Comment by dhinakg** [comment]
10.15 was added.
