### ISSUE TITLE
Poor GPU performance - Ryzen 5 3600 + GTX 1060

### ISSUE THREAD

**Issue by denmorgenshtern** [AMD-OSX/AMD_Vanilla#47]
I am running 10.13.6 (17G8037) with Ryzen 5 3600 + gtx 1060 6gb and I am noticing a very poor GPU performance, even with OS animations. Web drivers installed, offcourse.

This machine with intel CPU (i5 2500k + mobo for intel) worked great, even at games - i've played WoW on this mac :)

Can it be fixed or it's AMD-OSX trait?

**Comment by tedli** [comment]
Hi @denmorgenshtern ,

I also noticed this soon at the first boot after upgrade to 10.15. I didn't benchmark my GPU, but I can aware that OS animations is quite sticky at that time.

But what I also noticed that, the OS pop up with a notification, saying something like the OS is doing something like 'data upgrade', I didn't remember the exact words.

After a while, for now, everything works like before. OS animations OK. Still I didn't benchmark my GPU, and because I didn't get a GPU benchmark before upgrading to 10.15, I can't say we are in a same issue.

I just want to share that I also experienced poor OS animations, and without a touch on any of the patchs, it's now OK like before.

**Comment by collinkreutzer** [comment]
Was your machine on High Sierra before? As far as i know Nvidia didn't release WebDrivers since then so you won't get any hardware acceleration. Thats the reason most people use amd gpus in their hackintosh since they're mostly natively supported (Apple themselves only use AMD graphics cards today).

**Comment by denmorgenshtern** [comment]
Hi @tedli 
Do you use Nvidia GPU?
I am running 10.13.6 since 10.14 not supported by Nvidia driver. Does 10.15 supports it well?

Hi @collinkreutzer 
Yes, it was High Sierra - because of mentioned above 10.14 nvidia drivers problem. 
But on 10.13.6 Nvidia works well. Maybe 70-80% Windows performance, and I even could fully play World Of Warcraft without rebooting to Windows.

Now, on Ryzen CPU even switching tabs in SublimeText is a pain :D

**Comment by tedli** [comment]
Hi @denmorgenshtern

**Comment by collinkreutzer** [comment]
Hi. ;)
@tedli Wich AMD card and what kexts are you using? Im running fine on Vega 56 (with 64 Bios) and just Lilu/Whatevergreen on Catalina. Only resizing chrome stutters a bit wich seems normal as my MacBook does the same thing.

**Comment by dhinakg** [comment]
NVIDIA GPUs are known to have worse performance than AMD GPUs on AMD hackintoshes. I am not sure of the reason but I believe it is out of our control.

**Comment by 2535688890** [comment]
Can you share you Ryzen 3600 EFI for me?
