### ISSUE TITLE
Help me please : Some software( Parallel, Vmfusion, Camtasia) doesn't work on Amd cpu

### ISSUE THREAD

**Issue by djonko** [AMD-OSX/AMD_Vanilla#58]
I am trying to use Parallel, Vmfusion or Camtasia 2019 on my Ryzentosh for a week now but those software always crash on opening. but after test of many version of Camtasia I realize some previous version of 2016 can work. 

For Vmfusion(version 11) I have this error: "Transport VMDB) error-14: Pipe connection has broken"

For Parallel(version 14) I have this error: " The virtual machine processor was reset by the operating system."

I used everything here to set my config.plist and thanks to the team behind this great work.

Help me please, thanks in advance.
![Screen Shot 2019-10-20 at 10 41 39 PM](https://user-images.githubusercontent.com/2668809/67172839-e1bff180-f38a-11e9-8be3-dbda822b9a3d.png)
[report camtasia.txt](https://github.com/AMD-OSX/AMD_Vanilla/files/3748863/report.camtasia.txt)

**Comment by tedli** [comment]
Hi @djonko ,
I have been using VMware Fusion for about a year on AMD base hackintosh. Everything works as expect.
However the latest Fusion ( ver 11) dosen't run. The ver 10 Fusion dose. If you have license, you can try using the ver 10 Fusion.

Also since last month, I switched my vms to `VirtualBox`. VirtualBox also works great on AMD based hackintosh.

**Comment by djonko** [comment]
Thanks for replying me. Let me check VMware fusion 10 or VirtualBox then I will get back to you very soon.

**Comment by djonko** [comment]
Hi, VirtualBox is working very well but VMFusion 10 didn't work on my case. But thanks @tedli
