### ISSUE TITLE
Please add support for 10.15.1 (19B88) Security Update

### ISSUE THREAD

**Issue by kevinchen820** [AMD-OSX/AMD_Vanilla#64]

**Comment by IOIIIO** [comment]
Patches are being worked on. Currently experimental patches are in testing.

**Comment by dhinakg** [comment]
@kevinchen820 **__Experimental__** patches have been released for 10.15.1 for 17h. Please verify they work.
https://github.com/AMD-OSX/AMD_Vanilla/tree/experimental-clover/17h

**Comment by SandnerSoft** [comment]
Update from 10.15.0 to 10.15.1 ends with a kernel panic


![IMG_0284](https://user-images.githubusercontent.com/10620782/68077087-18036500-fdbe-11e9-8e9b-23f70ffad97d.jpg)

**Comment by dhinakg** [comment]
Given you were able to boot, the patches should be working fine. Just to make sure, please add the [disable kext logging patch](https://github.com/AMD-OSX/AMD_Vanilla/blob/f39b77269dc869319b10de4e7326b8bd59a52f46/17h/patches.plist#L25-L40) and take a new picture of the panic.

**Comment by SandnerSoft** [comment]
I have removed the logging from the config.plist, but the output stays the same.

**Comment by bdfish1104** [comment]
> @kevinchen820 ****Experimental**** patches have been released for 10.15.1 for 17h. Please verify they work.
> https://github.com/AMD-OSX/AMD_Vanilla/tree/experimental-clover/17h

Hi @dhinakg ,

I had tried your experimental-clover patch with the latest Clover version(5098). But the upgrade process hanged with a kernel panic. This panic could not be solved even I disabled the SMT in UEFI setting. My processor is AMD Ryzen 3600.

Thanks!

![P_20191103_113712](https://user-images.githubusercontent.com/57328203/68090362-27bb9180-fe30-11e9-9060-90811c2bcc62.jpg)

**Comment by dhinakg** [comment]
@SandnerSoft, you were supposed to add it, not remove it.
@bdfish1104, it seems like I messed up the patch backporting somewhere, I'll redo it and see if I made any mistakes anywhere.

**Comment by bdfish1104** [comment]
@dhinakg 
Thanks anyway! I could help to verify the new patch when it is available.

**Comment by SandnerSoft** [comment]
> @SandnerSoft, you were supposed to add it, not remove it.

With and without patch always the same error message.

**Comment by jsilvaigor** [comment]
Hi @dhinakg,

I'm having the same issue as @bdfish1104. My system is as Ryzen 5 3600 with an Asus B450M motherboard.
My test scenario is almost the same as his. 

![IMG_20191105_210642](https://user-images.githubusercontent.com/7428662/68257061-bedf3f80-0010-11ea-844d-df452642e5b0.jpg)

I'm also available to test the new patch when it's released. 
Thanks for the hard work. 😁

**Comment by Justatee** [comment]
@jsilvaigor  I think you should try OpenCore bootloader because this is only solution for AMD CPU hackintosh with macOS Catalina 10.15.1 right now. For more info try this:
[OpenCore github](https://github.com/acidanthera/OpenCorePkg)
[OpenCore vanilla guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/)

My PC spec running Catalina 10.15.1
CPU: Ryzen 5 3600
GPU: RX 5700 XT (Sapphire Pulse)
MB: MSI B450 mortar max

Everything work fine except Sleep / Wake (freezing after wake).

**Comment by icarapovic** [comment]
Can we use the experimental patches for USB install or is ist ATM only for upgrades? I would like to test on R7 3600X, Aorus Elite X570 + RX 5700.

**Comment by mikecole20** [comment]
I'm trying the experimental branch with 3700X, X570, 5700 XT. I end up with a black screen from HDMI and 2 of 3 DP. The last DP has some output but isn't usable.

**Comment by dhinakg** [comment]
@mikecole20, @icarapovic,
10.15.2 beta 1 has fixed the Navi issue where safe mode/installer/recovery had unusable graphics. However, you must be on OpenCore, as patches for 10.15.1 or 10.15.2 beta 1 have not been released yet for Clover. 10.15.2 beta 1 patches may or may not be released for Clover. 

The experimental patches are known to be broken. I should be uploading new experimental patches for 10.15.1 on Clover in the next day or two, but no guarantees.

**Comment by daihengfei** [comment]
@Justatee My PC and yours are similar, can you share your OpenCore boot file?

**Comment by mikecole20** [comment]
Same here. I made a pass at opencore the other day but didn't get it working. I'd appreciate a good starting point.

**Comment by Justatee** [comment]
Sorry bro for my bad English !!! @daihengfei , @mikecole20 I uploaded my EFI folder, hope it work with your PC (but I strongly recommend you make config.plist file by your self).

As @dhinakg noticed: "10.15.2 beta 1 has fixed the Navi issue where safe mode/installer/recovery had unusable graphics."  So I suggest you try this version instead of 10.15.1 

[EFI.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/3827228/EFI.zip)

**Comment by jamilbk** [comment]
I can attest that the experimental patches for 10.15.1 on Ryzen 17h seem to be working fine for me. I haven't made any modifications to them.

My system:

Threadripper 1950x
Four Vega Frontier Editions
Gigabyte Aorus Gaming 7 (AMD X399)
Killer 2500 Gigabit Ethernet

Here's the process I used to upgrade from 10.15.0:

1. Upgrade my existing clover to the latest revision (5098 at the time of this writing)
2. Install the latest Lilu (1.3.9) and WhateverGreen (1.3.4). Otherwise you may get a black screen.
2. Copy the new experimental patches
3. Reboot
4. Run the software updater to get 10.15.1 installed. For me, Clover automatically booted into the installer after the first reboot, so I didn't have to touch anything.

Good luck.

**Comment by mikecole20** [comment]
@Justatee it worked! Thanks so much. I'm planning on making a pass to compare your config w/ what I had originally tried to figure out what's different.

**Comment by kokowski** [comment]
@jamilbk Would you please instruct me how to copy the patches to a working config?

**Comment by zalivar71** [comment]
After update I can't to login into iMessage and Apple Music. Getting connection error

**Comment by bdfish1104** [comment]
The latest patch in the main branch could be used to upgrade to 10.15.1 now. Thanks for your work!
