### ISSUE TITLE
Native support Ryzen APUS 3000/4000

### ISSUE THREAD

**Issue by johnnync13** [AMD-OSX/AMD_Vanilla#90]
On 10.15.4 beta 1 appears Ryzen CPU...
Navi
https://twitter.com/_rogame/status/1225448569563471873
Ryzen
https://twitter.com/_rogame/status/1225381275617415168

**Comment by tedli** [comment]
As an irrelevant 3rd party, I'm very glade glad to hear that. :smile:

**Comment by IOIIIO** [comment]
Just because there is some random string in some random graphics kext does not mean anything.
Unless I see actual AMD code in the kernel it does not mean anything.

As Shaneee elegantly worded it:

Why do people just assume now that Apple will use AMD... Let me link you to the source of the 10.0 xnu file cpuid.c Yes Mac OS X Cheetah...
https://opensource.apple.com/source/xnu/xnu-123.5/osfmk/i386/cpuid.c.auto.html
You'll find it defines the AMD Vendor, CPUID_VID_AMD
Doesn't mean they ever added AMD CPU support...
As you go further AuthenticAMD was found in the xnu source. Again, AMD still wasn't supported.
Or this comment in Apple source code added ages ago:
 ```
       /*
         * Exception 15 is reserved but some chips may generate it
         * spuriously. Seen at startup on AMD Athlon-64.
         */
```

A random string appearing in a beta version of macOS does absolutely not indicate anything. It could easily have been a leftover of internal testing or even just a string they forgot to delete from code shipped by AMD.
